PrimatesGame/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/',include('PrimatesGameAPI.urls')),
    path('api/',include('djoser.urls')),
    path('api/',include('djoser.urls.authtoken')),
    path('accounts/', include('PrimatesGameAccount.urls')),
    path('', include('PrimatesGameWeb.urls')),
    path('game/', include('PrimatesGame_FixationTask.urls')),
    path('backend/', include('PrimatesGameBackEnd.urls'))
]

PrimatesGameAccount/urls.py
from django.contrib.auth import views
from django.urls import path
from .views import SignUpView

app_name = 'authen'

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('password-reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-change/', views.PasswordChangeView.as_view(), name='password_change'),
    path('password-change/done/', views.PasswordChangeDoneView.as_view(), name='password_change_done'), 
    ]

PrimatesGameWeb/urls.py
from django.urls import path , include
from . import views
from django.contrib.auth import views as authviews

app_name = 'webapp'

urlpatterns = [
    path("", views.home, name="home"),
    path('profile/<username>', views.profile, name='profile'),
    path("register-primates/", views.primates, name="register-primates"),
    path("start-game/", views.start_game, name="start-game"),
    path("standby/", views.standby, name="standby"),
    path("game_logout/", views.close_games, name="game_logout"),
    path("get-game-config-form/", views.get_game_config_form, name="get_game_config_form"),
    path('reports/', views.report_page, name='reports'),
    path('generate_csv/', views.generate_csv, name='generate_csv'),
]

PrimatesGameWeb/forms.py
from PrimatesGameAPI.models import RPiBoards , Primates , Games , Reports, FixationGameConfig, FixationGameReport
from django import forms 
from django.contrib.auth import get_user_model
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, HTML



class PrimatesForm(forms.Form):
    name = forms.CharField(max_length=255)
    
    

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username','first_name','last_name','email']
        
        
def validate_choice(value):
    if not(isinstance(value, int)):
        raise forms.ValidationError('Invalid choice selected')
    
class StartGameForm(forms.Form):
    def __init__(self, *args, **kwargs):
        rpi_name_list = RPiBoards.objects.filter(rpistates__is_occupied=False)  # Only include not occupied boards
        primate_name_list = Primates.objects.filter(is_occupied=False)  # Only include not occupied Primates
        game_name_list = Games.objects.all()
        report_list = Reports.objects.all()
        
        rpi_choices = [(int(obj.pk), obj.board_name) for obj in rpi_name_list]
        primate_choices = [(int(obj.pk),  obj.name) for obj in primate_name_list]
        game_choices = [(int(obj.pk), obj.name) for obj in game_name_list]
        report_choices = [(int(obj.pk), obj.reportname) for obj in report_list]
        
        super(StartGameForm, self).__init__(*args, **kwargs)
        if rpi_name_list and primate_name_list and game_name_list and report_list:
            self.fields['rpi_name'] = forms.ChoiceField(choices=rpi_choices)
            self.fields['primate_name'] = forms.ChoiceField(choices=primate_choices)
            self.fields['game_name'] = forms.ChoiceField(choices=game_choices)
            self.fields['report_name'] = forms.ChoiceField(choices=report_choices)
            
            
        self.helper = FormHelper()
        self.helper.layout = Layout(
            HTML('<select name="my_field" class="form-control">'),
            *[(int(pk), str(choice)) for pk, choice in game_choices],
            *[(int(pk), str(choice)) for pk, choice in rpi_choices],
            *[(int(pk), str(choice)) for pk, choice in primate_choices],
            *[(int(pk), str(choice)) for pk, choice in report_choices],
            HTML('</select>'),
            Submit('submit', 'Submit', css_class='btn btn-primary')
        )
    game_name = forms.ChoiceField(validators=[validate_choice])
    rpi_name = forms.ChoiceField( validators=[validate_choice])
    primate_name  = forms.ChoiceField(validators=[validate_choice])
    report_name = forms.ChoiceField(validators=[validate_choice])
    
    
class FixationGameConfigForm(forms.ModelForm):
    class Meta:
        model = FixationGameConfig
        fields = ["interval_correct", "interval_incorrect", "interval_absent", "button_holdDuration"]
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Set default values
        self.fields['interval_correct'].initial = 2  # Default value for interval_correct
        self.fields['interval_incorrect'].initial = 5  # Default value for interval_incorrect
        self.fields['interval_absent'].initial = 60  # Default value for interval_absent
        self.fields['button_holdDuration'].initial = 200  # Default value for botton_holdDuration
        
class ReportFilterForm(forms.Form):
    game = forms.ModelChoiceField(queryset=Games.objects.all(), required=True)
    start_date = forms.DateTimeField(widget=forms.TextInput(attrs={'type': 'datetime-local'}), required=True)
    end_date = forms.DateTimeField(widget=forms.TextInput(attrs={'type': 'datetime-local'}), required=True)
    board = forms.ModelChoiceField(queryset=RPiBoards.objects.all(), required=False, label="RPi Board")
    primate = forms.ModelChoiceField(queryset=Primates.objects.all(), required=False, label="Primate")

PrimatesGameWeb/views.py
from django.shortcuts import render , redirect
from .forms import PrimatesForm , UserUpdateForm , StartGameForm, FixationGameConfigForm, ReportFilterForm
from django.urls import reverse
from django.http import JsonResponse
import json
from django.contrib.auth import get_user_model
import requests
from PrimatesGameAPI.models import RPiBoards , Primates , Games , RPiStates , GameInstances , GameConfig, Reports, FixationGameReport, FixationGameResult
from django.contrib import messages
from datetime import datetime
from PrimatesGameAPI import views as APIviews
from django.http import HttpRequest , HttpResponse
from django.contrib.auth.models import User
from rest_framework.authtoken.models import Token
from django.http import Http404
from django.utils import timezone, dateformat
from django.views.decorators.csrf import csrf_exempt,csrf_protect
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import api_view, permission_classes
from PrimatesGameAPI.permissions import IsResearcher , IsRPiClient , IsAdmin ,  IsResearcherOrAdmin 
from django.template.loader import render_to_string
import csv


# Create your views here.
def home(request):
    rpi_states = RPiStates.objects.all()  # Retrieve all instances of YourModel
    
    # Get all experiments with status 'Running'
    running_experiments = RPiStates.objects.filter(is_occupied=True)
    
    # Check if all statuses are 'Running' (compare count with total experiments)
    all_running = running_experiments.count() == RPiStates.objects.count()
    
    # Get all primates with status 'occupied'
    unavailable_primates = Primates.objects.filter(is_occupied=True)
    
    # Check if all statuses are 'occupied' (compare count with total experiments)
    all_primates_unavailable = unavailable_primates.count() == Primates.objects.count()
    
    data = {
        "cards": [
            {"title": "Card 1", "text": "Content 1", "color": "primary"},
            {"title": "Card 2", "text": "Content 2", "color": "success"},
            {"title": "Card 3", "text": "Content 3", "color": "danger"},
        ],
        "experiments": [{"id":i, "name": rpi_state.rpiboard ,"status": "Running" if rpi_state.is_occupied else "Standby", "instance_name": GameInstances.objects.filter(id=rpi_state.game_instance_running).first(), "instance":rpi_state.game_instance_running} for i,rpi_state in enumerate(rpi_states)],
        "all_running": all_running,
        "all_primates_unavailable" : all_primates_unavailable,
    }
    
    
    #return render(request, "index.html",  {'rpi_states': rpi_states , 'user': request.user})
    return render(request, "index.html",  data)


def primates(request):
    if request.method == 'POST':
        form = PrimatesForm(request.POST)
        if form.is_valid():
            # Serialize the form data
            data = {
                'name': form.cleaned_data['name'],
            }
            
             # URL of the API endpoint
            url = request.build_absolute_uri(reverse('api:primates'))
            
            # Make a POST request to your API endpoint
            response = requests.post(url, data=data)
            if response.status_code == 201:
                # Return True to indicate javascript to process futher
                return JsonResponse({'success': True})
            # authenthication failed
            elif response.status_code == 401:
                return JsonResponse({'errors': 'Unauthorized'})
    else:
        form = PrimatesForm()
    return render(request, 'register-primates.html', {'form': form , 'user': request.user})


def start_game(request):
    '''
    Start the game manually
    Step of this view
    1. Start at start-game.html page, researchers initilizae the game by selecting
        - Raspberry Pi board that's available at the moment
        - Primate 
        - Game Type
        - Config of the game (config will be relative after selecting game, show only config for that game)
    
    
    '''

    def get_config_id(game_id):
        try:
            # Using get() to retrieve a single object
            config = GameConfig.objects.get(gameid=game_id)
            config_id = config.id
        except GameConfig.DoesNotExist:
            config_id = None
        
        return config_id
    
    if request.method == 'POST':
        form = StartGameForm(request.POST)
        config_form = FixationGameConfigForm(request.POST)
        

        if form.is_valid():

            
            ##### Create new gameinstance #########
            
            # Get current user in session
            user = User.objects.get(username=request.user)
            
            # Assuming you have already generated a token for the user
            token = Token.objects.get(user=user)

            #Serialize the form data
            
            print(form)
            
            rpiboard = form.cleaned_data['rpi_name']
            primate = form.cleaned_data['primate_name']
            game = form.cleaned_data['game_name']
            report_id = int(form.cleaned_data['report_name'])
            config = get_config_id(game)

            if config == None:
                raise Http404("Configuration does not exist")
            else:
                pass #### WHAT IS IT -> TO BE CHECkED

            # Create gameinstancename
            date_time = timezone.now()
            str_timezone = timezone.localtime(date_time).strftime("%Y-%m-%d_%H-%M")
            primate_name = Primates.objects.get(id=primate).name
            game_name = Games.objects.get(id=game).name
            # Create Gamereportname
            gameinstance_name = game_name + '_' +  primate_name + '_' + str_timezone
            
            data = {
                'name' : gameinstance_name,
               'rpiboard': rpiboard,
                'primate': primate,
                'game': game,
                'config' : config,
                'login_hist' : str(datetime.now())
            }
            #print(data)
            # Set up the request headers with the token
            headers = {
                'Authorization': f'Token {token}',
                'Content-Type': 'application/json'  # Adjust content type if necessary
            }
            # POST to /api/games-instances
            instance_url = request.build_absolute_uri(reverse('api:game-instance'))
            
            # Make a POST request to your API endpoint
            # Send the POST request with the data and headers
            response = requests.post(instance_url, json=data, headers=headers)
            #print(primate)
            #Update Primate Status -> Use Django
            primate_obj = Primates.objects.get(id=primate)
            primate_obj.is_occupied = True
            primate_obj.save()
            
            ###### game instance created successfully #######
            if response.status_code == 201:
                
                ####### Initialize game configuration  ########
                #print(response.json())
                # Access the ID of the newly created instance from the response
                game_instance_id = response.json().get('id')
                game_configtype_id = response.json().get('config')
                
                ### This section depends on configuration type ###
                
                if game_configtype_id == 1 and config_form.is_valid(): ## FixationGameConfig
                    
                    # Extract Fixation gameconfig
                    
                    interval_correct = config_form.cleaned_data['interval_correct']
                    interval_incorrect = config_form.cleaned_data['interval_incorrect']
                    interval_absent = config_form.cleaned_data['interval_absent']
                    button_holdDuration = config_form.cleaned_data['button_holdDuration']

                
                    #### Hard Code default  FixationGameConfig
                    data = {
                    'configtype': game_configtype_id,
                    'instance': game_instance_id,
                    'interval_correct': interval_correct,
                    'interval_incorrect' : interval_incorrect,
                    'interval_absent' : interval_absent,
                    'button_holdDuration':button_holdDuration # ms
                    }
                    
                    # POST to /api/fixationconfigs
                    config_url = request.build_absolute_uri(reverse('api:fixationconfigs'))
                    #print(url)
                
                
                response = requests.post(config_url, json=data, headers=headers)
                if response.status_code == 201:
                    ######### Initilize Report instance #########
                    date_time = timezone.now()
                    str_timezone = timezone.localtime(date_time).strftime("%Y-%m-%d_%H-%M")
                    #formatted_date = dateformat.format(
                    #                timezone.localtime(timezone.now()),
                    #               'Y-m-d H:i:s',
                    #                )
                    primate =  GameInstances.objects.get(id=game_instance_id).primate
                    
                    primate_name = Primates.objects.get(id=primate.id).name
                    report_name = Reports.objects.get(id=report_id).reportname
                    
                    # Create Gamereportname
                    gamereportname = report_name + '_' +  primate_name + '_' + str_timezone
                    
                    report_instance_data  ={
                        'report': report_id,
                        'instance': game_instance_id,
                        'gamereportname': gamereportname
                        }
                    
                    ### Report instance also depends on record type
                    print(type(report_id))

PrimatesGameWeb/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Dashboard{% endblock %}</title>
    <!-- Add Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Add custom CSS -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block extra_css %}{% endblock %}
</head>
<body>
    <!-- Navigation Bar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Dashboard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Experiments</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Settings</a>
                    </li>
                </ul>
                
                {% if user.is_authenticated %}
                <div class="d-flex ms-auto">
                <a href="#" class="btn btn-info me-2">{{ user.username }}</a>
                <a href="#" class="btn btn-danger" onclick="submitForm()">Logout</a>
                </div>
               {% else %}
                <!-- Green Login Button -->
                <a href="{% url 'authen:login' %}" class="btn btn-success ms-auto">Login</a>
               {% endif %}



            </div>
        </div>
    </nav>

    <!-- Main Content -->
    <div class="container-fluid mt-4">
        <div class="row">
            <!-- Sidebar -->
            <div class="col-md-2 bg-light p-3">
                <h5>Navigation</h5>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Overview</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Metrics</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'webapp:reports' %}">Reports</a>
                    </li>
                </ul>
            </div>

            <!-- Main Dashboard -->
            <div class="col-md-10">
                {% block content %}
                <!-- Default content can go here -->
                {% endblock %}
            </div>
        </div>
    </div>

    <!-- Add Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Add custom JS -->

    <script>
        const gameLogoutUrl = "{% url 'webapp:game_logout' %}";
    </script>
    
    <script src="{% static 'js/scripts.js' %}"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>

PrimatesGameWeb/templates/base_old.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Primal Game</title>
    <meta name="description" content="A brief description" />
    <meta
      name="author"
      content="loren ipsum"
    />

    <!-- Load favicon -->
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'img/favicon.ico' %}"
    />

    <!-- Include your CSS files here -->
    <link
      rel="preload"
      as="style"
      href="{% static 'css/style.css' %}"
      onload="this.rel = 'stylesheet'"
    />
    <link  rel="stylesheet"  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"  crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Karla&family=Markazi+Text:wght@500&display=swap"
      rel="stylesheet"
    />
  </head>

  <body>
    <!--Header content-->
    {% include 'partials/_header.html' %}

    <main>{% block content %} {% endblock %}</main>

    <!--Footer content-->
    {% include 'partials/_footer.html' %} 
    <!-- Replace this comment with your code  -->
  </body>
</html>

PrimatesGameWeb/templates/index.html
{% extends "base.html" %}

{% block title %}Dashboard - Home{% endblock %}

{% block content %}
<h3>Primates Research Dashboard</h3>

<!-- Cards Section -->
<div class="row">
    <div class="col-md-4">
        <div class="card text-white bg-primary mb-3">
            <div class="card-body">
                <h5 class="card-title">Card 1</h5>
                <p class="card-text">Some quick example text.</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card text-white bg-success mb-3">
            <div class="card-body">
                <h5 class="card-title">Card 2</h5>
                <p class="card-text">Some quick example text.</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card text-white bg-danger mb-3">
            <div class="card-body">
                <h5 class="card-title">Card 3</h5>
                <p class="card-text">Some quick example text.</p>
            </div>
        </div>
    </div>
</div>

<!-- Placeholder for charts -->
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Chart 1</h5>
                <div id="chart1">[Chart Placeholder]</div>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Chart 2</h5>
                <div id="chart2">[Chart Placeholder]</div>
            </div>
        </div>
    </div>
</div>


<!-- Table Section -->
<div class="card mt-4">
        {% if all_running and all_primates_unavailable %}
            <div class="card-body d-flex align-items-center">
                <h5 class="card-title mb-0 me-3">Experiment Table </h5>
                <h5 class="card-title mb-0 me-3" style="color:red;">All Devices and Primates Unavialable!</h5>
            </div>
        {% elif all_primates_unavailable %}
            <div class="card-body d-flex align-items-center">
                <h5 class="card-title mb-0 me-3">Experiment Table </h5>
                <h5 class="card-title mb-0 me-3" style="color:red;">All Primates Unavialable!</h5>
            </div>
        {% elif all_running %}
            <div class="card-body d-flex align-items-center">
                <h5 class="card-title mb-0 me-3">Experiment Table </h5>
                <h5 class="card-title mb-0 me-3" style="color:red;">All Devices Occupied!</h5>
            </div>
        {% else %}
            <div class="card-body d-flex align-items-center">
                <h5 class="card-title mb-0 me-3">Experiment Table </h5>
                <button class="btn btn-success btn-sm me-3" onclick="window.location.href='{% url 'webapp:start-game' %}'">Start Experiments</button>
            </div>
        {% endif %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Status</th>
                    <th>Experiment Running</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for experiment in experiments %}
                <tr id="row-{{ experiment.id }}">
                    <td>{{ experiment.id }}</td>
                    <td>{{ experiment.name }}</td>
                    <td>
                        {% if experiment.status == "Running" %}
                        <span style="display: inline-flex; align-items: center;">
                            <span class="rounded-circle d-inline-block" 
                                  style="width: 12px; height: 12px; background-color: green; margin-right: 5px;">
                            </span>
                            Running
                        </span>
                        {% else %}
                        <span style="display: inline-flex; align-items: center;">
                            <span class="rounded-circle d-inline-block" 
                                  style="width: 12px; height: 12px; background-color: orange; margin-right: 5px;">
                            </span>
                            Standby
                        </span>
                        {% endif %}
                    </td>
                    <td>{{ experiment.instance_name }}</td>
                    <td>
                        <button class="btn btn-sm btn-primary">View</button>
                        <!-- <button class="btn btn-sm btn-danger">Stop</button> -->
                        {% if experiment.status == "Running" %}
                        <button onclick="gameLogout('{{ experiment.instance }}')" class="btn btn-sm btn-danger">Stop</button>
                        {% else %}
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

PrimatesGameWeb/templates/index_old.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section>
  <article id="hero">
    <h1 class="heading_shadow">Start Experiment Here!</h1>
    <p>Current 0 PI board avialable</p>
    <a href="#" class="cta"> Launch Game </a>
  </article>
</section>
<section>
  <article>
    <h2>Experiment running</h2>
    <p>
      Current status of running experiment
    </p>
    {% for rpi_state in rpi_states %}
    <div>
      <div class="status-circle {% if rpi_state.is_occupied %}status-red{% else %}status-green{% endif %}"></div>
      <span>{{ rpi_state.rpiboard }}</span>
      <br>
    </div>
    {% endfor %}
  </article>
  <article>
    <h2>Login</h2>
    <p>
        Loren Ipsum
    </p>
    <p>
      <!-- Add code here for book  -->
      Loren Ipsum
    </p>
  </article>
  <article>
    <h2>Documentation</h2>
    <img src="{% static 'img/head_chef.jpg' %}" />
    <p>
      Start Here
    </p>
    <ul>
      <li>Installation</li>
      <li>Registration</li>
      <li>Instantiate the game</li>
      <li>Collect Record</li>
    </ul>
  </article>
</section>
{% endblock %}

PrimatesGameWeb/templates/profile.html
{% extends 'base.html' %} {% load static %} {% load crispy_forms_tags %} {% block content %}
<section>
    <article>
    <!-- Add your code in the line below  -->
    <legend class="border-bottom mb-4">Profile Information:</legend>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="media">
            <div class="media-body">
                <h2 class="account-heading">{{ form.instance.username }}

                </h2>
                <p class="text-secondary">{{ form.instance.first_name }} {{ form.instance.last_name }}</p>
                <p class="text-secondary">{{ form.instance.email }}</p>
            </div>
        </div>
    

        {% if user.username == form.instance.username %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Edit Profile Information</legend>
            <div class="form-row">
                <div class="form-group col-md-6 mb-0">
                    {{ form.first_name|as_crispy_field }}
                </div>
                <div class="form-group col-md-6 mb-0">
                    {{ form.last_name|as_crispy_field }}
                </div>
            </div> 
            {{ form.email|as_crispy_field }}

            <a href="{% url 'authen:password_reset' %}">Change password?</a>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
    {% endif %}
</form>
    </article>
</section>
{% endblock %}

PrimatesGameWeb/templates/reports.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Dashboard - Home{% endblock %}

{% block content %}
<div class="card mt-4">
    <div class="card-body">
        <div class="center_header">
            <h1>Generate Report</h1>
        </div>
        <section>
            <article>
                <form method="post">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit">Filter Reports</button>
                </form>

                {% if reports %}
                <h2>Select a Report</h2>
                <form method="get" action="{% url 'webapp:generate_csv' %}">
                    <label for="report-select">Available Reports:</label>
                    <select name="report_id" id="report-select" required>
                        {% for report in reports %}
                        <option value="{{ report.id }}">{{ report.gamereportname }}</option>
                        {% endfor %}
                    </select>
                    <button type="submit" style="background-color: green; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; margin-top: 10px;">
                        Download Selected Report
                    </button>
                </form>
                {% else %}
                    {% if no_reports_message %}
                    <p style="color: red; font-weight: bold;">{{ no_reports_message }}</p>
                    {% endif %}
                {% endif %}
            </article>
        </section>
    </div>
</div>
{% endblock %}

PrimatesGameWeb/templates/standby.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stand By</title>
    <style>
        body {
            margin: 0;
            background-color: black;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            color: white;
            font-family: Arial, sans-serif;
            font-size: 48px;
        }
    </style>
</head>
<body>
    STANDBY
</body>
</html>

PrimatesGameWeb/templates/start-game_backup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}Dashboard - Home{% endblock %}

{% block content %}
<div class="card mt-4">
    <div class="card-body">
        <div class="center_header">
            <h3>Start the Experiment</h3>
        </div>
        <section>
            <article>
            <!--Begin row-->
            <div class="center_startgame">
                <!-- Add your code in the line below  -->
                    <form method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button  type="submit"  class="btn btn-success">Submit </button>
                    </form>
            </div>
            <!--End row-->
            </article>
        </section>
    </div>
</div>

{% endblock %}